name: Deploy Posy (production)

on:
  push:
    tags: ["posy-v*"]

jobs:
  production:
    permissions:
      contents: read
    uses: ./.github/workflows/app-deploy.yml # zizmor: ignore[secrets-inherit]
    with:
      app: posy
      environment: production
      url: https://play.posy.workers.dev
    secrets: inherit
