name: Posy deploy (production)

on:
  push:
    tags: ["posy-v*"]

jobs:
  production:
    permissions:
      contents: read
    uses: ./.github/workflows/target-cloudflare.yml # zizmor: ignore[secrets-inherit]
    with:
      app: posy
      environment: production
      url: https://play.posy.workers.dev
      d1: true
      sentry-org: sdrmme
      sentry-project: posy
    secrets: inherit
