name: Posy deploy (staging)

on:
  push:
    branches: [main]
    paths:
      - apps/posy/**
      - packages/**
      - pnpm-lock.yaml
      - .github/workflows/target-cloudflare.yml
      - .github/workflows/posy-deploy-staging.yml
      - .github/actions/setup/**

jobs:
  staging:
    permissions:
      contents: read
    uses: ./.github/workflows/target-cloudflare.yml # zizmor: ignore[secrets-inherit]
    with:
      app: posy
      environment: staging
      url: https://staging.posy-stg.workers.dev
      d1: true
      seed: true
      sentry-org: sdrmme
      sentry-project: posy
    secrets: inherit
