name: Deploy Posy (staging)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - apps/posy/**
      - packages/**
      - pnpm-lock.yaml
      - .github/workflows/target-cloudflare.yml
      - .github/workflows/posy-deploy-staging.yml
      - .github/actions/setup/**
  push:
    branches: [main]
    paths:
      - apps/posy/**
      - packages/**
      - pnpm-lock.yaml
      - .github/workflows/target-cloudflare.yml
      - .github/workflows/posy-deploy-staging.yml
      - .github/actions/setup/**

jobs:
  preview:
    if: github.event_name == 'pull_request' && !startsWith(github.head_ref, 'release-please--')
    permissions:
      contents: read
    uses: ./.github/workflows/target-cloudflare.yml # zizmor: ignore[secrets-inherit]
    with:
      app: posy
      environment: preview
      branch: ${{ github.head_ref }}
      workers-subdomain: posy-stg
      d1: true
      seed: true
      sentry-org: sdrmme
      sentry-project: posy
    secrets: inherit

  staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
    uses: ./.github/workflows/target-cloudflare.yml # zizmor: ignore[secrets-inherit]
    with:
      app: posy
      environment: staging
      url: https://staging.posy-stg.workers.dev
      d1: true
      seed: true
      sentry-org: sdrmme
      sentry-project: posy
    secrets: inherit
